name: pylint
on: [pull_request]
jobs:
  run-pylint:
    name: Run-pylint
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install pansat package
        run: pip install .
      - name: Install pylint
        run: pip install pylint
      - name: Lint Code Base
      # omit conventions and minimum score is 7.5
        run: pylint pansat --disable=C --fail-under=7.5
